export const IMAGES = {
  STRENGTH: '/img/ability/STRENGTH.png',
  SPEED: '/img/ability/SPEED.png',
  INTELLIGENCE: '/img/ability/INTELLIGENCE.png',
  BEAUTY: '/img/ability/BEAUTY.png',
  TIGER: '/img/result/TIGER.png',
  SNAIL: '/img/result/SNAIL.png',
  CHIMP: '/img/result/CHIMP.png',
  GOLDFISH: '/img/result/GOLDFISH.png',
  SLOTH: '/img/result/SLOTH.png',
  CHEETAH: '/img/result/CHEETAH.png',
  PROBOSCIS_MONKEY: '/img/result/PROBOSCIS_MONKEY.png',
  WOLF: '/img/result/WOLF.png',
  SPINNER: '/icon/spinner.svg',
  WORLD: '/icon/world.png',
  SOUND: '/icon/sound.png',
  SOUND_MUTE: '/icon/sound-mute.png',
  RIGHT_ARROW: 'icon/right-arrow.png',
  LEFT_ARROW: 'icon/left-arrow.png',
};
