name: End-to-End test
on: [push, pull_request]
    branches:
      - 'master'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v3

      - name: pre E2E
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000

      - name: Cypress run
        run: npm run build